name: CI / Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [24.x, 25.x, 26.x]
    name: ${{ matrix.os }} - v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: Setup pnpm and build
        run: npm i -g pnpm@11.5.0; pnpm -v
      - run: pnpm i
      - run: pnpm run build
  